import "../../globals.css";
import roboto from "../../../constants/localFonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans`}>
        <div className="bg-gray-200">{children}</div>
      </body>
    </html>
  );
}
